[package]
name = "my-wordle"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.x"
rand = "0.8.5"
rand_chacha = "0.3.x"
rocket = { version = "0.5.1", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
